name: c-icesat-2
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  - jupyter
  - jupyterlab
  - xarray
  - numpy
  - scipy
  - dask
  - dask-jobqueue
  - netcdf4
  - pandas
  - matplotlib
  - ipykernel
  - seaborn
  - f90nml
  